version: '3.2'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - '27017:27017'

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - '6379:6379'
