### get a user
GET http://localhost:4860/api/v1/users/bd2501c6-b149-47b3-9755-22fa3109bdff


### update a user info
PATCH  http://localhost:4860/api/v1/users/bd2501c6-b149-47b3-9755-22fa3109bdff HTTP/1.1
Content-Type: application/json

{
  "name": "John Smith 2"
}
